!function()
{function t(t)
 {if(t.querySelector("img")&&null===t.getAttribute("no-icon"))
 {var e=document.createElement("img");e.classList.add("ar-icon"),
   e.setAttribute("src","https://storage.kakucho-ar.com/img/ar-icon.png"),
   e.setAttribute("style","width: 35px; height: 35px; border-radius: 50%; position: absolute; top: 10px; right: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, .1);"),
   t.appendChild(e),t.style.position="relative"}}function e(e){var n=e.getAttribute("ios-src");n&&/.+\.(usdz|reality)/.test(n)?(t(e),
   e.addEventListener("click",(function(t){t.preventDefault();var e=document.createElement("a");
   e.setAttribute("rel","ar"),e.setAttribute("href",n),e.appendChild(document.createElement("img")),e.click()}),!1)):e.addEventListener("click",(function(t){t.preventDefault()}),!1)}function n(e){var n=e.getAttribute("href");n&&/.+\.(glb|gltf)/.test(n)?(t(e),e.addEventListener("click",(function(t){t.preventDefault();var r=document.createElement("a");r.setAttribute("href",function(t,e,n){var r=location.toString(),o=new URL(t,r),i=o.protocol.replace(":",""),a="?file="+encodeURIComponent(o.toString())+"&mode=ar_preferred&link="+r+"&title="+encodeURIComponent(e);if(n){var c=new URL(n,r);a+="&sound=".concat(encodeURIComponent(c.toString()))}return"intent://arvr.google.com/scene-viewer/1.0"+a+"#Intent;scheme="+i+";package=com.google.ar.core;action=android.intent.action.VIEW;end;"}(n,e.getAttribute("alt")||"",e.getAttribute("sound"))),r.click()}),!1)):e.addEventListener("click",(function(t){t.preventDefault()}),!1)}function r(t){t.addEventListener("click",(function(t){t.preventDefault()}),!1)}var o,i=/android/i.test(navigator.userAgent),a=(o=document.createElement("a")).relList&&o.relList.supports&&o.relList.supports("ar"),c=function(t,e){return new CustomEvent("initAR",{detail:{os:t,arSupported:e}})};document.addEventListener("DOMContentLoaded",(function(){var t,o=Array.prototype.slice.call(document.querySelectorAll('a[href$=".glb"],a[href$=".gltf"],a[ios-src$=".usdz"],a[ios-src$=".reality"]'),0);a?(document.body.classList.add("ar-supported"),o.forEach(e),t=c("ios",!0)):i?(document.body.classList.add("ar-supported"),o.forEach(n),t=c("android",!0)):(document.body.classList.add("ar-unsupported"),o.forEach(r),t=c("unknown",!1)),document.dispatchEvent(t)}))}();
